# This file is a template, and might need editing before it works on your project.
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  SERVER: https://docker-dab.addvalue.it:16443
  CERTIFICATE_AUTHORITY_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQVBWSlU4QURHaDMvTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU1ERXlNRGN4TnpJNU1qRmFGdzB6TURFeU1EVXhOekk1TWpGYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFMTlorTWNKandOci8rSzdxNTJxc2hpTG9XUmk0UzVNUjI5cWlMdU5ZR0pxOUk5Q2VSUzcKSlhoUUVHMGo2RFgxam5aVEhSaTAwUEVuMGR5Um1zYUZHaEdpcG9OblBSTThLelZ6TUNQbFRsbVFwdDN5ZDNhaApGWHNzZTU0WHJTVmJPZXJDMURRazRmalppUjBIL3JORnRJUmZta3l1ZkgwYUtpbWx2TXBYdkNXbjA5dm9FaFA0CnBJMWhGSmRYSC9UR29VVUw2UERPc1VHbThKWXFtV1o1dkorMndaSnZnN0VlQi9Sa1haeE1LbVdGWmNWM20wNzgKRy9udXgwbEZFSHlMZjlrU3hwaHdCbVBXV3h3NnhlU0Z3UlhDQlhlZFZNQXZ3dCtNTW53eXMrMytHL1BpcUdJaAp2aFVZSUJDaXhLYWUyd1dmT0xnbDZkSnYxK1g1MHVnRXl6c0NBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGRkVYCjFJbWN5NnJ4NngvZldvNjVxWnpVY3Z6Y01COEdBMVVkSXdRWU1CYUFGRkVYMUltY3k2cng2eC9mV282NXFaelUKY3Z6Y01Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURWaWtxaDZvcE9iQVBiOApGcTZFTDJBQUJZNGdaTityM1FLeG5RVFMrSXJXS1J2ck9Od21QOEZPWnVmekI3eGRCenZjVTJOY24rSHZMbzJDCklaUkxkd1ZPcnBzeWxzU2lGNEVldGNxUHJhMStmUDZsUFZ4R3pGOVJBdWN2TnpaNmNVQitVNWpJSDEzTUF0VE8KeW44NHMzMURJMmtwV3FhdFhXWWlORG1KZXkrdTR4STg5cDN0Uk0xa0tLRTBZZk5PTkNGOG1wc2tDNFRrbGlRcwpxTFRYN01xb2lENEl5RlRtRSt5WjZQYkhzczE1OVN2bGVxU2Fabnl2ZXluQm1LTkljVmQwY2VkTnc2dGNEcUdoCmhoNVZ6VjdSdUNHMmQ5UXNVR0xkWSs3OVc1ZGh3L2UvRUtONlo5RG9ibzJPNUxSM3ZnMlR5YnVGcUVNU2Q0LzQKUCthYkI1Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  USER_TOKEN:  eyJhbGciOiJSUzI1NiIsImtpZCI6InlHTUlqUGFIbHV3YXZ1bUNpcWk1MEwtRXA2cUs5NHd6NzZfYlZFVEhELU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJnaXRsYWItYWRtaW4tdG9rZW4tajh0ZGYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ2l0bGFiLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGVhNmQ4OGUtYWM3NC00YzM4LTgxNTQtNWMwYjY2OTM0MTA4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmdpdGxhYi1hZG1pbiJ9.CdzIsi1KwbuJmJ4YyIUA2MXq01d3RcyGM_MXAZxhwee8eVmKsCHubrs8g_P4qs7kdFLdDE5NknrtUuyGniVour-gJVaBbgACEQmbYEUSUcEuamKlYxU8lU-7hwF4Lwicb6_EkzrKWcyHA7fSnVy89EYr-CNiXAEXPfhZmNmojzbtJfK3794MmkLSrJZlEDpcHjx9ymVvq7K6HvUPMJOZ58XkT2FMbArGHRwfq6HRmAAywAZUhVAVjj0AoosqUBFEIG9of2HzQDlf9KHpQtjAYualX0tixpfNpCQPbDDcIAHTadwSm5K0nnolH8C1xBSyFqXIp3CTkelTDX0EPgWZeA


docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script: 
    ##- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u acavalieri -p 3Q37cTUc6XZj3e7 $CI_REGISTRY
    ##- docker login docker-dab.addvalue.it:32000
  script:
    - docker build . -t acavalieri/k8s
    - docker push acavalieri/k8s
    #- docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    #- docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f deployment.yaml
    - kubectl rollout status deployment.v1.apps/spring-boot-k8s-deployment
