# This file is a template, and might need editing before it works on your project.
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  SERVER: https://docker-dab.addvalue.it:16443
  CERTIFICATE_AUTHORITY_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQUtLYTQ2U2VSZVZlTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU1ERXlNRGd4T1RJd05UaGFGdzB6TURFeU1EWXhPVEl3TlRoYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFMK1kydmE3U09GZGlEM21ZREJwU0hYZjkwbUVORmI0NkYyVXVzaDVDUCs3U242c0RsV2cKUHROYjZIbERsNTYwbVJtQ0llWW9sYlQ3KzlpeFhHOWVQeENlekhQSUNuMGFwRGc0WFFtbktiblJvVGt3OGJ2OAovbTQvRGRhdGo4S250YjVaSUpYQkVXOVhCbVpwd2RlbU12U3ZqZy9Yb2tyUThXVDA0ckJNUkthcjBNNm96Y0gxCkhlbks2WFg0MGg3dEpOdkdwQWV2amZ3MWQxQnFSejM1ZFN5QlczMEpna0VUWFhUYTdZOEtrd3gxdHJmRmhtVzcKeHBpYkZleDQ3OXNRclordkRNK3lqYkwzWnd6VkhrekZXZExkdU81OEZveCtjbkE0QmdkMTFKV0JxRlpjSXdQOAp4L09lNEVJVjZxSC9Bb0NRa0tqY2NUeVhzOVd5MytLQW1GVUNBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGRDZXClFHL3RwN21FSWdQZ0FGVTExelk2bEpsak1COEdBMVVkSXdRWU1CYUFGRDZXUUcvdHA3bUVJZ1BnQUZVMTF6WTYKbEpsak1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUl5R1lRb3h5VC9yOURXcAovZ1pTZ2lwaGs5Q2ZzQXU4UkduSDBERnpDRVRVWWpmYlFOUWZaaVc3ZENxOW1OcDlsd0JWZmZoR1lOL3V3cThCCnZJemExN0QvMnlnMmdyQVE5WktEQ0h3MEtaU25VT1JlMWNwUUNTbVE0VUR6N2tEUTdLaXpjZGp5L1ZMbFIwU0EKaDJ2YXdnc0l3VG9iaFQ4OW9PZDlOSjI0WWFYL21DSFRJRHVxa09tK1ZUN2R1ek15WUQycm9Yb20vdkxjRzJ3bwpMUWpuRS9palM0S1ptdlZoOHFmVTlhQ2x1S3NvWlZwQTdmVXBPbHF5cFdiMFJtWUdkM3QyMW53MnJzRko2TWpQCkZZRUVkMEYzMUJIU3pYUkZJSXRlUWgxMDNzQWFSUXU5WWxBMyt1WFFZcXhNTjhCTzE5L3ZlTWRVWEN3UTBBek8KbTdDMExKVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  USER_TOKEN:  eyJhbGciOiJSUzI1NiIsImtpZCI6IkRQRHJhS2xoVUUtV2M3QzFUQXFqakM2Ukp6WU41ZXdYaG10RnRxQVZGdkUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tcWs3aDkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQzM2JhMDQ1LWY1MzMtNGQ4Mi04NmNmLTA2ZDIyZDM0NDBhZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.D1tulSopQoNKQ5wDtaXHmfhZKwDyAIOhsvKcapNinRe771a9-A2MS6gg2N7yyoSRet9mpRC7YaZoIErK1vnnyzqzXxbsQJ1g8OiMxF5Ym8bJgz_7-qix-iGqPiaIGekOm4kG_PU0U-iw5V3nYMXfrHRz_L8cTCL36Oij2mTq0P8Cr8cMYNyirGGg0Qcy-WSa-qNouhvN4bbxnpRVLY7rxoN4j6VFif3xTLyFgIToToLPyxJpytNh0xQaQ7QJtY0v2-R-dAvcvI66ZjKJTAt7QRiY5xVgAQIl-Yb1YGoQkRDEMLsczZVdwEb73L_cize-OGjrJPgCOznn7tEUPZIEWQ

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script: 
    ##- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u acavalieri -p 3Q37cTUc6XZj3e7 $CI_REGISTRY
    ##- docker login docker-dab.addvalue.it:32000
  script:
    - docker build . -t acavalieri/k8s
    - docker push acavalieri/k8s
    #- docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    #- docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f deployment.yaml
    - kubectl rollout status deployment.v1.apps/spring-boot-k8s-deployment
