# This file is a template, and might need editing before it works on your project.
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  SERVER: https://docker-dab.addvalue.it:16443
  CERTIFICATE_AUTHORITY_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEQVRDQ0FlbWdBd0lCQWdJSkFKRWxOK0NrNi85NU1BMEdDU3FHU0liM0RRRUJDd1VBTUJjeEZUQVRCZ05WDQpCQU1NRERFd0xqRTFNaTR4T0RNdU1UQWVGdzB5TURFd01qZ3lNekkzTWpkYUZ3MHpNREV3TWpZeU16STNNamRhDQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQDQpBRENDQVFvQ2dnRUJBTGhvNUtMS3JCVWw3a0YwM08ySW1PV2ZTTTlLN3R4T3BsZUk4a2MxajNKNGlsMFVBT2Q4DQpxUmFtWmpVeERWalZmck41NFdUeU5EdkJkMlhRdm4xSGhzSWJTVm0xOWlaeEx6YUN5UGVJWktZbHdLeTBsampiDQpCWUpkUmlWbFEzZmN4UUR1MENiMFRIdGUwNXBLMlcrRFRuR2owN1Yyb08ycWNRU3dVbXVVc0d6YkI1QTUxdWI5DQpPY0VFOFRCVGp0U1ZRcStIM2pmRUFrMzk4MThHeThjMnpxa2pVRFA3YnN4ZkhxUkVGR0d0elJiZ3pzTXZDeW04DQpTV0pMRzJSNHJKVEtOZjlIdXFHRlZHNitnRG54Y3ZoNnRrZU9mUXRPY2xxVEZwM3VvaTB6ZXVyU3FJOSt3Q2Z2DQpZTGtTUkduMW95NVpqakRDaEZSNVVqT1V3VVFGdlJrMEQyOENBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGQVBhDQpPWVN1YjlWMGxmaXBaNnFuYWRFM0xLZ0NNQjhHQTFVZEl3UVlNQmFBRkFQYU9ZU3ViOVYwbGZpcFo2cW5hZEUzDQpMS2dDTUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSWUwbDZhTk40K3FLUGp6DQpFZzRVWEFLaUZGRkxCN1ovYm9QYVhxWlE3cDh1QmoxVGJlcmJLY2g5eFpKUWUxTjM2UVRSejJvbko4NCtTM3BRDQpsSHRIV3Z2cmJmRDV1USsrT256SVhucmoybkFUMDF6Z1AveHp4aVJNNXRJc0tQODEydGNxdUZpVjhZVnZ5S2tBDQpzUHdoT1BUSlF5ZEt0RytOU1B4eVZlMithS2R0eC9lbllzNzRqQVZrYXNvMlpZUGI1dUZneFpDVFYzU255WFV2DQpveUZGZFRKSFJ4aEhmZmpRbmZLL2JrdXdnYVY2ekZuWnQvczhNaG5reFZTaU4raW9zemN0aDJvTng2OFFzTmJQDQpSVGxRV1JRTWt5SlZ3clZKY1QySlhKQ2VON1VLUDgwRFFnMHZHenkzUUJOTlFVQlFmN0hlMTYvNDQyQVpnZngrDQo0Ui9BN0pNPQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  USER_TOKEN:  eyJhbGciOiJSUzI1NiIsImtpZCI6InlHTUlqUGFIbHV3YXZ1bUNpcWk1MEwtRXA2cUs5NHd6NzZfYlZFVEhELU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJnaXRsYWItYWRtaW4tdG9rZW4tajh0ZGYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ2l0bGFiLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGVhNmQ4OGUtYWM3NC00YzM4LTgxNTQtNWMwYjY2OTM0MTA4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmdpdGxhYi1hZG1pbiJ9.CdzIsi1KwbuJmJ4YyIUA2MXq01d3RcyGM_MXAZxhwee8eVmKsCHubrs8g_P4qs7kdFLdDE5NknrtUuyGniVour-gJVaBbgACEQmbYEUSUcEuamKlYxU8lU-7hwF4Lwicb6_EkzrKWcyHA7fSnVy89EYr-CNiXAEXPfhZmNmojzbtJfK3794MmkLSrJZlEDpcHjx9ymVvq7K6HvUPMJOZ58XkT2FMbArGHRwfq6HRmAAywAZUhVAVjj0AoosqUBFEIG9of2HzQDlf9KHpQtjAYualX0tixpfNpCQPbDDcIAHTadwSm5K0nnolH8C1xBSyFqXIp3CTkelTDX0EPgWZeA


docker-build:
  # Official docker image.
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script: 
    ##- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u acavalieri -p 3Q37cTUc6XZj3e7 $CI_REGISTRY
    ##- docker login docker-dab.addvalue.it:32000
  script:
    - docker build . -t acavalieri/k8s
    - docker push acavalieri/k8s
    #- docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    #- docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

deploy:
  stage: build
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f deployment.yaml
